# Generated by Django 3.2.4 on 2021-10-07 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='نام شرکت')),
                ('address', models.TextField(blank=True, max_length=1000, null=True, verbose_name='آدرس شرکت')),
                ('tel', models.CharField(blank=True, max_length=100, null=True, verbose_name='تلفن های شرکت')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت شرکت')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت ها',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='نام')),
                ('mobile', models.CharField(max_length=20, unique=True, verbose_name='تلفن همراه')),
                ('level', models.CharField(choices=[('1', 'عضو'), ('2', 'مدیر گروه'), (3, 'مدیر ارشد')], max_length=2, verbose_name='نوع عضویت')),
                ('password', models.CharField(max_length=100, verbose_name='رمز عبور')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.company', verbose_name='نام شرکت')),
            ],
            options={
                'verbose_name': 'عضو شرکت',
                'verbose_name_plural': 'اعضای شرکت ها',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='نام گروه')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد گروه')),
                ('blacklist', models.ManyToManyField(blank=True, related_name='blacklists_teams', to='core.Member', verbose_name='لیست سیاه')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='core.company', verbose_name='نام شرکت')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers_teams', to='core.member', verbose_name='مدیر گروه')),
                ('members', models.ManyToManyField(blank=True, to='core.Member', verbose_name='اعضای گروه')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners_teams', to='core.member', verbose_name='مدیر ارشد گروه')),
            ],
            options={
                'verbose_name': 'تیم(گروه)',
                'verbose_name_plural': 'تیم ها(گروه ها)',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member', verbose_name='عضو')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team', verbose_name='گروه')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locdate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('locdata', models.CharField(max_length=200, verbose_name='اطلاعات مکان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.member', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مکان کاربر',
                'verbose_name_plural': 'مکان کاربران',
            },
        ),
    ]
