# Generated by Django 3.2.4 on 2021-10-01 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='نام شرکت')),
                ('address', models.TextField(blank=True, max_length=1000, null=True, verbose_name='آدرس شرکت')),
                ('tel', models.CharField(blank=True, max_length=100, null=True, verbose_name='تلفن های شرکت')),
                ('team_count', models.IntegerField(verbose_name='تعدا گروه های شرکت')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت شرکت')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت ها',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.account')),
                ('level', models.IntegerField(default=1)),
                ('last_loc', models.CharField(blank=True, max_length=100, null=True, verbose_name='اطلاعات آخرین مکان')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name': 'عضو شرکت',
                'verbose_name_plural': 'اعضای شرکت ها',
            },
            bases=('account.account',),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='نام گروه')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد گروه')),
                ('black_list', models.ManyToManyField(blank=True, related_name='black_list', to='core.Member', verbose_name='لیست سیاه')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='core.company', verbose_name='نام شرکت')),
                ('team_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_manager', to='core.member', verbose_name='مدیر گروه')),
                ('team_members', models.ManyToManyField(blank=True, related_name='team_members', to='core.Member', verbose_name='اعضای گروه')),
                ('team_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_owner', to='core.member', verbose_name='مدیر ارشد گروه')),
            ],
            options={
                'verbose_name': 'تیم(گروه)',
                'verbose_name_plural': 'تیم ها(گروه ها)',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=50, verbose_name='ماه و سال')),
                ('loc_data', models.CharField(max_length=200, verbose_name='اطلاعات مکان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.member', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مکان کاربر',
                'verbose_name_plural': 'مکان کاربران',
            },
        ),
    ]
