# Generated by Django 3.2.4 on 2021-06-29 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('mobile', models.CharField(max_length=20, unique=True, verbose_name='تلفن همراه')),
                ('level', models.IntegerField(default=1)),
                ('last_loc', models.CharField(blank=True, max_length=100, null=True, verbose_name='اطلاعات آخرین مکان')),
                ('name', models.CharField(max_length=400, verbose_name='نام و نام خانوادگی')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='مدیرکل')),
                ('is_staff', models.BooleanField(default=False, verbose_name='کارمند')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ عضویت')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کابر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='نام شرکت')),
                ('address', models.TextField(blank=True, max_length=1000, null=True, verbose_name='آدرس شرکت')),
                ('tel', models.CharField(blank=True, max_length=100, null=True, verbose_name='تلفن های شرکت')),
                ('team_count', models.IntegerField(verbose_name='تعدا گروه های شرکت')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ عضویت شرکت')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='مدیر شرکت')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت ها',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='نام گروه')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد گروه')),
                ('black_list', models.ManyToManyField(blank=True, related_name='black_list', to=settings.AUTH_USER_MODEL, verbose_name='لیست سیاه')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='core.company', verbose_name='نام شرکت')),
                ('team_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_manager', to=settings.AUTH_USER_MODEL, verbose_name='مدیر گروه')),
                ('team_members', models.ManyToManyField(blank=True, related_name='team_members', to=settings.AUTH_USER_MODEL, verbose_name='اعضای گروه')),
                ('team_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_owner', to=settings.AUTH_USER_MODEL, verbose_name='مدیر ارشد گروه')),
            ],
            options={
                'verbose_name': 'گروه',
                'verbose_name_plural': 'گروه ها',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=50, verbose_name='ماه و سال')),
                ('loc_data', models.CharField(max_length=200, verbose_name='اطلاعات مکان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مکان کاربر',
                'verbose_name_plural': 'مکان کاربران',
            },
        ),
    ]
